# Generated by Django 5.1.4 on 2025-02-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
