# Generated by Django 5.0.10 on 2025-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_played_game',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_played',
            field=models.FloatField(default=0.0),
        ),
    ]
